package router

import (
	"fmt"
	"net/http"
	"net/url"
	"os"

	"github.com/gin-gonic/gin"
	"github.com/pipigendut/dating-backend/docs"
	v1 "github.com/pipigendut/dating-backend/router/api/v1"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

type GlobalHandlers struct {
	V1 *v1.Handlers
}

type GlobalConfig struct {
	AppEnv         string
	V1Config       v1.RouterConfig
	AuthMiddleware gin.HandlerFunc
}

// swaggerMultiVersionHTML serves a custom Swagger UI page with a version dropdown selector.
// It uses the native Swagger UI `urls` config option which adds a "Select a definition" dropdown.
const swaggerMultiVersionHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>API Documentation</title>
  <link rel="stylesheet" type="text/css" href="/swagger/v1/swagger-ui.css" >
  <link rel="icon" type="image/png" href="/swagger/v1/favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="/swagger/v1/favicon-16x16.png" sizes="16x16" />
  <style>
    html { box-sizing: border-box; overflow: -moz-scrollbars-vertical; overflow-y: scroll; }
    *, *:before, *:after { box-sizing: inherit; }
    body { margin: 0; background: #fafafa; }
  </style>
</head>
<body>
<div id="swagger-ui"></div>
<script src="/swagger/v1/swagger-ui-bundle.js"></script>
<script src="/swagger/v1/swagger-ui-standalone-preset.js"></script>
<script>
window.onload = function() {
  const ui = SwaggerUIBundle({
    urls: [
      { url: "/swagger/v1/doc.json", name: "V1 - Current" }
    ],
    "urls.primaryName": "V1 - Current",
    dom_id: '#swagger-ui',
    validatorUrl: null,
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout",
    docExpansion: "list",
    deepLinking: true,
    defaultModelsExpandDepth: 1,
    persistAuthorization: true,
  })
  window.ui = ui
}
</script>
</body>
</html>`

func SetupRouter(r *gin.Engine, h *GlobalHandlers, cfg GlobalConfig) {
	// Configure dynamic swagger host
	baseURL := os.Getenv("BASE_URL")
	if baseURL != "" {
		if u, err := url.Parse(baseURL); err == nil {
			docs.SwaggerInfo.Host = u.Host
			docs.SwaggerInfo.Schemes = []string{u.Scheme}
		}
	}

	// 1. Global / Root Routes

	// Deep Linking
	r.GET("/invite", h.V1.Group.HandleInviteRedirect)
	r.GET("/invite/:token", h.V1.Group.HandleInviteRedirect)

	// Universal Links
	r.Static("/.well-known", fmt.Sprintf("./well-known/%s", cfg.AppEnv))

	// 2. Swagger Routes
	// Single entry point with version selector at /swagger/index.html
	r.GET("/swagger", func(c *gin.Context) {
		c.Redirect(http.StatusMovedPermanently, "/swagger/index.html")
	})
	r.GET("/swagger/index.html", func(c *gin.Context) {
		c.Header("Content-Type", "text/html; charset=utf-8")
		c.String(http.StatusOK, swaggerMultiVersionHTML)
	})

	// Serve Swagger assets and doc.json per version instance
	// V1: serves CSS, JS bundles, and doc.json for v1
	r.GET("/swagger/v1/*any", ginSwagger.WrapHandler(swaggerFiles.Handler,
		ginSwagger.InstanceName("swagger"), // default instance generated by swag init
		ginSwagger.URL("doc.json"),
	))

	// 3. Register Versioned API Routes
	v1.RegisterRoutes(r, h.V1, cfg.V1Config)

	// Health check
	r.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "OK"})
	})
}
